### ISSUE TITLE
Response returns InvalidRequesterror()

### ISSUE THREAD

**Issue by bharatk101-dckap** [tomas-net/ip2geotools#4]
Tried with the example given in the document but it returns InvalidRequesterror()

```
from ip2geotools.databases.noncommercial import DbIpCity
response = DbIpCity.get('147.229.2.90', api_key='free')
response.ip_address 
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sbc/anaconda3/lib/python3.7/site-packages/ip2geotools/databases/noncommercial.py", line 60, in get
    raise InvalidRequestError()
ip2geotools.errors.InvalidRequestError
```

**Comment by tomas-net** [comment]
What is your Python version? I have just tested it on Python 3.4.3 without any problems.

**Comment by Ostyk** [comment]
I'm having the same problem right now, regardless of version. I think it has to do with the Server side, because the same code worked yesterday and this morning. Tried it out on different platforms/python versions/networks.

**Comment by Ostyk** [comment]
yeah, it works today just fine.

**Comment by Ostyk** [comment]
> I'm having the same problem right now, regardless of version. I think it has to do with the Server side, because the same code worked yesterday and this morning. Tried it out on different platforms/python versions/networks.

yeah today it works fine, so it must have been some connection issue on the server side

**Comment by tomas-net** [comment]
bharatk101-dckap: Can you confirm it is connection issue on the server side.

**Comment by Ostyk** [comment]
Ok, I think that it is not even the connection issue, but the api that you are using timed me out due to the large number of requests. I read that I'd have to purchuse a lisence to have so many daily requests. Thanks anyways, it is stilll a great way to access their API.
