### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by Pythack** [tomas-net/ip2geotools#7]
I can't download this module, here is the error:
`Collecting ip2geotools
  Using cached https://files.pythonhosted.org/packages/97/de/addc2a0db7e2584f3fa960549c15439cfab70c30935ee453fb938e75de6e/ip2geotools-0.1.4.tar.gz
Requirement already satisfied: Click==7.0 in /usr/lib/python2.7/dist-packages (from ip2geotools) (7.0)
Collecting IP2Location==8.0.3 (from ip2geotools)
  Using cached https://files.pythonhosted.org/packages/b3/ec/0ea7279a022fc2fb98c680fce8c7527486a927c67f855aba18b4af30e06d/IP2Location-8.0.3.tar.gz
Collecting Pygments==2.3.0 (from ip2geotools)
  Using cached https://files.pythonhosted.org/packages/fc/41/4f900a7852e25bb9350b4e3ee8c4aba0ee32abefd401456962b25f954823/Pygments-2.3.0-py2.py3-none-any.whl
Collecting astroid==2.1.0 (from ip2geotools)
  Could not find a version that satisfies the requirement astroid==2.1.0 (from ip2geotools) (from versions: 1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.5.0, 1.5.1, 1.5.2, 1.5.3, 1.6.0, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6)
No matching distribution found for astroid==2.1.0 (from ip2geotools)
`

**Comment by tomas-net** [comment]
You are using old version (0.1.4) instead of the latest one (0.1.5). And also this package is intended for Python 3+.
